import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BarChart3,Building2,Leaf,LogOut,RefreshCw,Search,ShieldCheck,ShoppingCart,Users} from 'lucide-react';
import './admin.css';

const API=(import.meta.env.VITE_API_URL||'http://localhost:8000').replace(/\/$/,'');
const sizeOptions=['unclassified','individual','micro','small','mid_size','large','enterprise'];
const categoryOptions=['unclassified','individual_consumer','hobbyist_collector','florist_landscaper','professional_grower','botanical_garden','nursery_garden_center','farm_agriculture_business','small_business','mid_size_business','large_enterprise','government_agency','university','research_institution','nonprofit_ngo','conservation_organization','other'];
const pretty=value=>(value||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());

async function api(path,options={}){
  const headers={'Content-Type':'application/json',...(options.headers||{})};
  return fetch(`${API}${path}`,{credentials:'include',...options,headers});
}

function Stat({icon:Icon,label,value,sub}){return <article className="stat"><span className="stat-icon"><Icon/></span><div><small>{label}</small><strong>{value}</strong><p>{sub}</p></div></article>}
function Bars({title,data}){const rows=Object.entries(data||{}).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...rows.map(([,v])=>v));return <section className="panel"><h3>{title}</h3>{rows.length?rows.map(([k,v])=><div className="bar-row" key={k}><div className="bar-label"><span>{pretty(k)}</span><b>{v}</b></div><div className="bar-track"><i style={{width:`${Math.max(4,(v/max)*100)}%`}}/></div></div>):<p className="muted">No segment data yet.</p>}</section>}

function AdminApp(){
 const [me,setMe]=useState(null),[overview,setOverview]=useState(null),[segments,setSegments]=useState(null),[participants,setParticipants]=useState([]),[activity,setActivity]=useState([]),[role,setRole]=useState('vendor'),[size,setSize]=useState(''),[category,setCategory]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const profile=await api('/api/v1/auth/me');if(!profile.ok)throw new Error('Sign in with an administrator account first.');const user=await profile.json();if(user.role!=='admin')throw new Error('This page is restricted to BloomAI administrators.');setMe(user);const qs=new URLSearchParams({role});if(size)qs.set('organization_size',size);if(category)qs.set('category',category);const [o,s,p,a]=await Promise.all([api('/api/v1/admin/analytics/overview'),api('/api/v1/admin/analytics/segments'),api(`/api/v1/admin/participants?${qs}`),api('/api/v1/admin/activity?limit=40')]);for(const r of [o,s,p,a])if(!r.ok)throw new Error('Admin analytics could not be loaded.');setOverview(await o.json());setSegments(await s.json());setParticipants((await p.json()).items);setActivity(await a.json())}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[role,size,category]);
 const shown=useMemo(()=>participants.filter(p=>`${p.name} ${p.email} ${p.organization_name||''} ${p.country||''}`.toLowerCase().includes(query.toLowerCase())),[participants,query]);
 async function classify(person){const organization_size=prompt('Organization size: individual, micro, small, mid_size, large, enterprise',person.organization_size);if(!organization_size||!sizeOptions.includes(organization_size))return;const nextCategory=prompt('Category (e.g. botanical_garden, government_agency, university, research_institution)',person.category);if(!nextCategory||!categoryOptions.includes(nextCategory))return;const organization_name=prompt('Organization name (optional)',person.organization_name||'')||null;const country=prompt('Country (optional)',person.country||'')||null;const industry=prompt('Industry / sector (optional)',person.industry||'')||null;const r=await api(`/api/v1/admin/participants/${person.user_id}/segment`,{method:'PATCH',body:JSON.stringify({organization_size,category:nextCategory,organization_name,country,industry})});if(r.ok)load();else alert('Could not update this participant.')}
 async function logout(){await api('/api/v1/auth/logout',{method:'POST'});location.href='/'}
 if(error)return <main className="gate"><Leaf/><h1>BloomAI Admin</h1><p>{error}</p><a href="/">Return to marketplace</a></main>;
 if(loading||!overview||!segments)return <main className="gate"><RefreshCw className="spin"/><p>Loading marketplace intelligence…</p></main>;
 const seg=segments[role]||{};
 return <div className="admin-shell"><aside><a href="/" className="brand"><Leaf/>BloomAI</a><nav><a className="active"><BarChart3/>Overview</a><a href="#participants"><Users/>Participants</a><a href="#activity"><ShoppingCart/>Activity</a></nav><div className="admin-user"><ShieldCheck/><span><b>{me?.name}</b><small>Administrator</small></span></div></aside><main><header><div><span className="eyebrow">Marketplace intelligence</span><h1>Admin reporting & analytics</h1><p>Track customer, vendor and commercial activity across BloomAI.</p></div><div className="header-actions"><button onClick={load}><RefreshCw/>Refresh</button><button onClick={logout}><LogOut/>Logout</button></div></header>
 <section className="stats"><Stat icon={Users} label="Marketplace users" value={overview.users.total} sub={`${overview.users.new_last_30_days} joined in 30 days`}/><Stat icon={Building2} label="Vendors" value={overview.users.vendors} sub={`${overview.users.customers} customers`}/><Stat icon={ShoppingCart} label="Orders" value={overview.commerce.orders} sub={`${overview.commerce.paid_orders} paid`}/><Stat icon={BarChart3} label="Gross revenue" value={overview.commerce.gross_revenue.toLocaleString(undefined,{maximumFractionDigits:2})} sub={`${overview.commerce.revenue_last_30_days.toLocaleString(undefined,{maximumFractionDigits:2})} last 30 days`}/></section>
 <div className="toolbar"><div className="tabs"><button className={role==='vendor'?'active':''} onClick={()=>setRole('vendor')}>Vendors</button><button className={role==='customer'?'active':''} onClick={()=>setRole('customer')}>Customers</button></div><select value={size} onChange={e=>setSize(e.target.value)}><option value="">All sizes</option>{sizeOptions.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categoryOptions.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></div>
 <section className="charts"><Bars title={`${pretty(role)} by organization size`} data={seg.by_size}/><Bars title={`${pretty(role)} by category`} data={seg.by_category}/></section>
 <section id="participants" className="panel wide"><div className="panel-head"><div><h3>{pretty(role)} directory</h3><p>Click Segment to classify or reclassify an account.</p></div><label className="search"><Search/><input placeholder="Search name, email or organization" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Organization</th><th>Size</th><th>Category</th><th>Country</th><th>Activity</th><th/></tr></thead><tbody>{shown.map(p=><tr key={p.user_id}><td><b>{p.name}</b><small>{p.email}</small></td><td>{p.organization_name||'—'}</td><td><span className="pill">{pretty(p.organization_size)}</span></td><td>{pretty(p.category)}</td><td>{p.country||'—'}</td><td>{p.role==='customer'?`${p.activity.orders} orders · ${p.activity.paid_spend.toFixed(2)} spent`:`${p.activity.products} products · ${p.activity.orders_received} orders · ${p.activity.gross_sales.toFixed(2)} sales`}</td><td><button className="segment" onClick={()=>classify(p)}>Segment</button></td></tr>)}</tbody></table></div></section>
 <section id="activity" className="panel wide"><h3>Recent marketplace activity</h3><div className="activity">{activity.map((item,i)=><div key={`${item.type}-${i}`}><span className="dot"/><div><b>{item.summary}</b><small>{pretty(item.type)} · {new Date(item.occurred_at).toLocaleString()}</small></div>{item.amount!=null&&<strong>{item.currency} {item.amount.toFixed(2)}</strong>}</div>)}</div></section>
 </main></div>}

createRoot(document.getElementById('admin-root')).render(<AdminApp/>);
