import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,BarChart3,Building2,Download,FileText,Globe2,Leaf,LogOut,RefreshCw,Search,ShieldCheck,ShoppingCart,TrendingUp,Users} from 'lucide-react';
import './admin.css';

const API=(import.meta.env.VITE_API_URL||'http://localhost:8000').replace(/\/$/,'');
const sizeOptions=['unclassified','individual','micro','small','mid_size','large','enterprise'];
const categoryOptions=['unclassified','individual_consumer','hobbyist_collector','florist_landscaper','professional_grower','botanical_garden','nursery_garden_center','farm_agriculture_business','small_business','mid_size_business','large_enterprise','government_agency','university','research_institution','nonprofit_ngo','conservation_organization','other'];
const pretty=value=>(value||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
const money=value=>Number(value||0).toLocaleString(undefined,{maximumFractionDigits:2});

async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};return fetch(`${API}${path}`,{credentials:'include',...options,headers});}
function Stat({icon:Icon,label,value,sub}){return <article className="stat"><span className="stat-icon"><Icon/></span><div><small>{label}</small><strong>{value}</strong><p>{sub}</p></div></article>}
function Bars({title,data,valueSuffix=''}){const rows=Object.entries(data||{}).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...rows.map(([,v])=>Math.abs(v)));return <section className="panel"><h3>{title}</h3>{rows.length?rows.map(([k,v])=><div className="bar-row" key={k}><div className="bar-label"><span>{pretty(k)}</span><b>{v}{valueSuffix}</b></div><div className="bar-track"><i style={{width:`${Math.max(4,(Math.abs(v)/max)*100)}%`}}/></div></div>):<p className="muted">No data yet.</p>}</section>}
function Trend({title,rows,valueKey,labelKey,format=v=>v}){const max=Math.max(1,...(rows||[]).map(row=>Number(row[valueKey]||0)));return <section className="panel"><h3>{title}</h3><div className="trend-list">{(rows||[]).length?(rows||[]).map(row=><div className="trend-row" key={row[labelKey]}><span>{row[labelKey]}</span><div className="trend-track"><i style={{width:`${Math.max(3,(Number(row[valueKey]||0)/max)*100)}%`}}/></div><b>{format(row[valueKey])}</b></div>):<p className="muted">No activity in this period.</p>}</div></section>}

function AdminApp(){
 const [me,setMe]=useState(null),[overview,setOverview]=useState(null),[segments,setSegments]=useState(null),[executive,setExecutive]=useState(null),[participants,setParticipants]=useState([]),[activity,setActivity]=useState([]),[role,setRole]=useState('vendor'),[size,setSize]=useState(''),[category,setCategory]=useState(''),[query,setQuery]=useState(''),[months,setMonths]=useState(12),[inactiveDays,setInactiveDays]=useState(90),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const profile=await api('/api/v1/auth/me');if(!profile.ok)throw new Error('Sign in with an administrator account first.');const user=await profile.json();if(user.role!=='admin')throw new Error('This page is restricted to BloomAI administrators.');setMe(user);const qs=new URLSearchParams({role});if(size)qs.set('organization_size',size);if(category)qs.set('category',category);const [o,s,e,p,a]=await Promise.all([api('/api/v1/admin/analytics/overview'),api('/api/v1/admin/analytics/segments'),api(`/api/v1/admin/executive/dashboard?months=${months}&inactive_days=${inactiveDays}`),api(`/api/v1/admin/participants?${qs}`),api('/api/v1/admin/activity?limit=40')]);for(const r of [o,s,e,p,a])if(!r.ok)throw new Error('Admin analytics could not be loaded.');setOverview(await o.json());setSegments(await s.json());setExecutive(await e.json());setParticipants((await p.json()).items);setActivity(await a.json())}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[role,size,category,months,inactiveDays]);
 const shown=useMemo(()=>participants.filter(p=>`${p.name} ${p.email} ${p.organization_name||''} ${p.country||''}`.toLowerCase().includes(query.toLowerCase())),[participants,query]);
 async function classify(person){const organization_size=prompt('Organization size: individual, micro, small, mid_size, large, enterprise',person.organization_size);if(!organization_size||!sizeOptions.includes(organization_size))return;const nextCategory=prompt('Category (e.g. botanical_garden, government_agency, university, research_institution)',person.category);if(!nextCategory||!categoryOptions.includes(nextCategory))return;const organization_name=prompt('Organization name (optional)',person.organization_name||'')||null;const country=prompt('Country (optional)',person.country||'')||null;const industry=prompt('Industry / sector (optional)',person.industry||'')||null;const r=await api(`/api/v1/admin/participants/${person.user_id}/segment`,{method:'PATCH',body:JSON.stringify({organization_size,category:nextCategory,organization_name,country,industry})});if(r.ok)load();else alert('Could not update this participant.')}
 async function logout(){await api('/api/v1/auth/logout',{method:'POST'});location.href='/'}
 function download(path){window.location.assign(`${API}${path}`)}
 if(error)return <main className="gate"><Leaf/><h1>BloomAI Admin</h1><p>{error}</p><a href="/">Return to marketplace</a></main>;
 if(loading||!overview||!segments||!executive)return <main className="gate"><RefreshCw className="spin"/><p>Loading marketplace intelligence…</p></main>;
 const seg=segments[role]||{},k=executive.kpis||{};
 const growthData=Object.fromEntries((executive.category_growth||[]).slice(0,10).map(x=>[x.category,x.growth_percent]));
 return <div className="admin-shell"><aside><a href="/" className="brand"><Leaf/>BloomAI</a><nav><a className="active" href="#executive"><TrendingUp/>Executive</a><a href="#segments"><BarChart3/>Segments</a><a href="#participants"><Users/>Participants</a><a href="#activity"><ShoppingCart/>Activity</a></nav><div className="admin-user"><ShieldCheck/><span><b>{me?.name}</b><small>Administrator</small></span></div></aside><main><header><div><span className="eyebrow">Executive marketplace intelligence</span><h1>Admin reporting & analytics</h1><p>Revenue, growth, retention, vendor performance and marketplace risk in one operating view.</p></div><div className="header-actions"><button onClick={load}><RefreshCw/>Refresh</button><button onClick={()=>download('/api/v1/admin/executive/export.csv')}><Download/>CSV</button><button onClick={()=>download('/api/v1/admin/executive/export.pdf')}><FileText/>PDF</button><button onClick={logout}><LogOut/>Logout</button></div></header>
 <section id="executive" className="stats executive-stats"><Stat icon={TrendingUp} label="Gross revenue" value={money(k.gross_revenue)} sub="Paid marketplace orders"/><Stat icon={ShoppingCart} label="Average order value" value={money(k.average_order_value)} sub={`${k.active_buyers} active buyers`}/><Stat icon={Activity} label="Checkout conversion" value={`${k.checkout_conversion_rate}%`} sub="Paid ÷ initiated orders"/><Stat icon={Users} label="Repeat purchase rate" value={`${k.repeat_purchase_rate}%`} sub={`${k.repeat_buyers} repeat buyers`}/><Stat icon={Globe2} label="Inactive accounts" value={k.inactive_accounts} sub={`No activity for ${inactiveDays}+ days`}/><Stat icon={Building2} label="Vendors" value={overview.users.vendors} sub={`${overview.users.customers} customers`}/></section>
 <div className="executive-controls"><label>Trend window<select value={months} onChange={e=>setMonths(Number(e.target.value))}><option value="6">6 months</option><option value="12">12 months</option><option value="24">24 months</option><option value="36">36 months</option></select></label><label>Inactive threshold<select value={inactiveDays} onChange={e=>setInactiveDays(Number(e.target.value))}><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option><option value="180">180 days</option><option value="365">365 days</option></select></label></div>
 <section className="charts executive-charts"><Trend title="Revenue trend" rows={executive.revenue_trends} labelKey="month" valueKey="revenue" format={money}/><Trend title="Customer acquisition" rows={executive.customer_acquisition} labelKey="month" valueKey="new_customers"/><Bars title="Category growth · last 30d vs prior 30d" data={growthData} valueSuffix="%"/></section>
 <section className="panel wide"><div className="panel-head"><div><h3>Vendor performance ranking</h3><p>Ranked by paid gross sales, then paid order volume.</p></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Vendor</th><th>Organization</th><th>Revenue</th><th>Paid orders</th><th>Unique customers</th><th>Products</th></tr></thead><tbody>{executive.vendor_ranking.map((v,i)=><tr key={v.vendor_id}><td>{i+1}</td><td><b>{v.vendor_name}</b></td><td>{v.organization_name||'—'}</td><td>{money(v.revenue)}</td><td>{v.paid_orders}</td><td>{v.unique_customers}</td><td>{v.products}</td></tr>)}</tbody></table></div></section>
 <section className="charts"><section className="panel"><h3>Geographic marketplace heatmap</h3><p className="muted">Intensity reflects paid revenue; participant counts show marketplace reach.</p><div className="geo-grid">{executive.geography.slice(0,24).map((g,index)=><div key={g.country} className={`geo-cell heat-${Math.min(5,Math.floor(index/5))}`}><b>{g.country}</b><strong>{money(g.revenue)}</strong><small>{g.customers} customers · {g.vendors} vendors</small></div>)}</div></section><section className="panel"><h3>Inactive-account detection</h3><p className="muted">Accounts with no recorded order, product or marketplace transaction activity within the selected threshold.</p><div className="inactive-list">{executive.inactive_accounts.slice(0,12).map(x=><div key={x.user_id}><span><b>{x.name}</b><small>{pretty(x.role)} · {x.country||'Unclassified'}</small></span><strong>{x.inactive_days}d</strong></div>)}{!executive.inactive_accounts.length&&<p className="muted">No inactive accounts at this threshold.</p>}</div></section></section>
 <section id="segments"><div className="toolbar"><div className="tabs"><button className={role==='vendor'?'active':''} onClick={()=>setRole('vendor')}>Vendors</button><button className={role==='customer'?'active':''} onClick={()=>setRole('customer')}>Customers</button></div><select value={size} onChange={e=>setSize(e.target.value)}><option value="">All sizes</option>{sizeOptions.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categoryOptions.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></div><section className="charts"><Bars title={`${pretty(role)} by organization size`} data={seg.by_size}/><Bars title={`${pretty(role)} by category`} data={seg.by_category}/></section></section>
 <section id="participants" className="panel wide"><div className="panel-head"><div><h3>{pretty(role)} directory</h3><p>Click Segment to classify or reclassify an account.</p></div><label className="search"><Search/><input placeholder="Search name, email or organization" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Organization</th><th>Size</th><th>Category</th><th>Country</th><th>Activity</th><th/></tr></thead><tbody>{shown.map(p=><tr key={p.user_id}><td><b>{p.name}</b><small>{p.email}</small></td><td>{p.organization_name||'—'}</td><td><span className="pill">{pretty(p.organization_size)}</span></td><td>{pretty(p.category)}</td><td>{p.country||'—'}</td><td>{p.role==='customer'?`${p.activity.orders} orders · ${p.activity.paid_spend.toFixed(2)} spent`:`${p.activity.products} products · ${p.activity.orders_received} orders · ${p.activity.gross_sales.toFixed(2)} sales`}</td><td><button className="segment" onClick={()=>classify(p)}>Segment</button></td></tr>)}</tbody></table></div></section>
 <section id="activity" className="panel wide"><h3>Recent marketplace activity</h3><div className="activity">{activity.map((item,i)=><div key={`${item.type}-${i}`}><span className="dot"/><div><b>{item.summary}</b><small>{pretty(item.type)} · {new Date(item.occurred_at).toLocaleString()}</small></div>{item.amount!=null&&<strong>{item.currency} {item.amount.toFixed(2)}</strong>}</div>)}</div></section>
 </main></div>}

createRoot(document.getElementById('admin-root')).render(<AdminApp/>);
