import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,BarChart3,Building2,Download,FileText,Globe2,Leaf,LogOut,MapPin,Minus,Plus,RefreshCw,Search,ShieldCheck,ShoppingCart,TrendingUp,Users} from 'lucide-react';
import './admin.css';

const API=(import.meta.env.VITE_API_URL||'http://localhost:8000').replace(/\/$/,'');
const WORLD_GEOJSON='https://cdn.jsdelivr.net/gh/johan/world.geo.json@master/countries.geo.json';
const sizeOptions=['unclassified','individual','micro','small','mid_size','large','enterprise'];
const categoryOptions=['unclassified','individual_consumer','hobbyist_collector','florist_landscaper','professional_grower','botanical_garden','nursery_garden_center','farm_agriculture_business','small_business','mid_size_business','large_enterprise','government_agency','university','research_institution','nonprofit_ngo','conservation_organization','other'];
const pretty=value=>(value||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
const money=value=>Number(value||0).toLocaleString(undefined,{maximumFractionDigits:2});

async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};return fetch(`${API}${path}`,{credentials:'include',...options,headers});}
function Stat({icon:Icon,label,value,sub}){return <article className="stat"><span className="stat-icon"><Icon/></span><div><small>{label}</small><strong>{value}</strong><p>{sub}</p></div></article>}
function Bars({title,data,valueSuffix=''}){const rows=Object.entries(data||{}).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...rows.map(([,v])=>Math.abs(v)));return <section className="panel"><h3>{title}</h3>{rows.length?rows.map(([k,v])=><div className="bar-row" key={k}><div className="bar-label"><span>{pretty(k)}</span><b>{v}{valueSuffix}</b></div><div className="bar-track"><i style={{width:`${Math.max(4,(Math.abs(v)/max)*100)}%`}}/></div></div>):<p className="muted">No data yet.</p>}</section>}
function Trend({title,rows,valueKey,labelKey,format=v=>v}){const max=Math.max(1,...(rows||[]).map(row=>Number(row[valueKey]||0)));return <section className="panel"><h3>{title}</h3><div className="trend-list">{(rows||[]).length?(rows||[]).map(row=><div className="trend-row" key={row[labelKey]}><span>{row[labelKey]}</span><div className="trend-track"><i style={{width:`${Math.max(3,(Number(row[valueKey]||0)/max)*100)}%`}}/></div><b>{format(row[valueKey])}</b></div>):<p className="muted">No activity in this period.</p>}</div></section>}

function polygonPath(ring){return ring.map(([lon,lat],index)=>`${index?'L':'M'}${((lon+180)/360)*1000},${((90-lat)/180)*500}`).join(' ')+' Z'}
function featurePath(feature){const geometry=feature.geometry;if(!geometry)return'';if(geometry.type==='Polygon')return geometry.coordinates.map(polygonPath).join(' ');if(geometry.type==='MultiPolygon')return geometry.coordinates.flatMap(polygon=>polygon.map(polygonPath)).join(' ');return''}
function WorldMap({points=[],geography=[],coverage={}}){
 const [world,setWorld]=useState([]),[mapError,setMapError]=useState(''),[selected,setSelected]=useState(null),[roleFilter,setRoleFilter]=useState('all'),[zoom,setZoom]=useState(1);
 useEffect(()=>{let active=true;fetch(WORLD_GEOJSON).then(r=>{if(!r.ok)throw new Error('Map boundaries unavailable');return r.json()}).then(data=>{if(active)setWorld(data.features||[])}).catch(()=>{if(active)setMapError('World boundaries could not be loaded; country aggregates remain available below.')});return()=>{active=false}},[]);
 const filtered=points.filter(point=>roleFilter==='all'||point.role===roleFilter);
 const revenueByCountry=Object.fromEntries((geography||[]).map(row=>[String(row.country||'').toLowerCase(),Number(row.revenue||0)]));
 const maxRevenue=Math.max(1,...Object.values(revenueByCountry));
 const countryOpacity=feature=>{const name=String(feature.properties?.name||'').toLowerCase();const revenue=revenueByCountry[name]||0;return revenue?0.18+0.62*(revenue/maxRevenue):0.08};
 return <section className="panel world-map-panel"><div className="panel-head map-head"><div><h3>Interactive world marketplace map</h3><p>Country shading reflects paid revenue. Precise markers use stored participant latitude/longitude.</p></div><div className="map-controls"><select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)} aria-label="Map participant role"><option value="all">All participants</option><option value="customer">Customers</option><option value="vendor">Vendors</option></select><button type="button" onClick={()=>setZoom(z=>Math.min(2.4,z+.2))} aria-label="Zoom in"><Plus/></button><button type="button" onClick={()=>setZoom(z=>Math.max(1,z-.2))} aria-label="Zoom out"><Minus/></button><button type="button" onClick={()=>setZoom(1)}>Reset</button></div></div><div className="map-coverage"><span><b>{coverage.geocoded||0}</b> mapped</span><span><b>{coverage.ungeocoded||0}</b> awaiting coordinates</span><span><b>{coverage.coverage_rate||0}%</b> coverage</span></div>{mapError?<p className="map-error">{mapError}</p>:<div className="map-stage"><svg viewBox="0 0 1000 500" role="img" aria-label="World map of BloomAI customers and vendors"><g style={{transform:`scale(${zoom})`,transformOrigin:'500px 250px'}}>{world.map(feature=><path key={feature.id||feature.properties?.name} d={featurePath(feature)} className="country-shape" style={{fillOpacity:countryOpacity(feature)}}><title>{feature.properties?.name}</title></path>)}{filtered.map(point=>{const x=((Number(point.longitude)+180)/360)*1000,y=((90-Number(point.latitude))/180)*500;return <circle key={`${point.user_id}-${point.role}`} cx={x} cy={y} r={point.role==='vendor'?6:5} className={`map-marker ${point.role}`} onClick={()=>setSelected(point)} tabIndex="0" role="button" onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(point)}}}><title>{point.name} · {point.city||point.country||'Mapped location'}</title></circle>})}</g></svg></div>}{selected&&<div className="map-selection"><MapPin/><div><b>{selected.name}</b><span>{pretty(selected.role)} · {[selected.city,selected.region,selected.country].filter(Boolean).join(', ')||'Mapped location'}</span><small>{selected.organization_name||pretty(selected.category)} · activity value {money(selected.value)}</small></div><button type="button" onClick={()=>setSelected(null)}>Close</button></div>}<div className="map-legend"><span><i className="legend-dot customer"/>Customer</span><span><i className="legend-dot vendor"/>Vendor</span><span>Country revenue remains the fallback for participants without coordinates.</span></div></section>
}

function AdminApp(){
 const [me,setMe]=useState(null),[overview,setOverview]=useState(null),[segments,setSegments]=useState(null),[executive,setExecutive]=useState(null),[participants,setParticipants]=useState([]),[activity,setActivity]=useState([]),[role,setRole]=useState('vendor'),[size,setSize]=useState(''),[category,setCategory]=useState(''),[query,setQuery]=useState(''),[months,setMonths]=useState(12),[inactiveDays,setInactiveDays]=useState(90),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const profile=await api('/api/v1/auth/me');if(!profile.ok)throw new Error('Sign in with an administrator account first.');const user=await profile.json();if(user.role!=='admin')throw new Error('This page is restricted to BloomAI administrators.');setMe(user);const qs=new URLSearchParams({role});if(size)qs.set('organization_size',size);if(category)qs.set('category',category);const [o,s,e,p,a]=await Promise.all([api('/api/v1/admin/analytics/overview'),api('/api/v1/admin/analytics/segments'),api(`/api/v1/admin/executive/dashboard?months=${months}&inactive_days=${inactiveDays}`),api(`/api/v1/admin/participants?${qs}`),api('/api/v1/admin/activity?limit=40')]);for(const r of [o,s,e,p,a])if(!r.ok)throw new Error('Admin analytics could not be loaded.');setOverview(await o.json());setSegments(await s.json());setExecutive(await e.json());setParticipants((await p.json()).items);setActivity(await a.json())}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[role,size,category,months,inactiveDays]);
 const shown=useMemo(()=>participants.filter(p=>`${p.name} ${p.email} ${p.organization_name||''} ${p.country||''} ${p.city||''}`.toLowerCase().includes(query.toLowerCase())),[participants,query]);
 async function classify(person){const organization_size=prompt('Organization size: individual, micro, small, mid_size, large, enterprise',person.organization_size);if(!organization_size||!sizeOptions.includes(organization_size))return;const nextCategory=prompt('Category (e.g. botanical_garden, government_agency, university, research_institution)',person.category);if(!nextCategory||!categoryOptions.includes(nextCategory))return;const organization_name=prompt('Organization name (optional)',person.organization_name||'')||null;const country=prompt('Country (optional)',person.country||'')||null;const address_line1=prompt('Street / address line (optional)',person.address_line1||'')||null;const city=prompt('City (optional)',person.city||'')||null;const region=prompt('State / province / region (optional)',person.region||'')||null;const postal_code=prompt('Postal code (optional)',person.postal_code||'')||null;const latitudeText=prompt('Latitude for map marker (-90 to 90, optional)',person.latitude??'');const longitudeText=prompt('Longitude for map marker (-180 to 180, optional)',person.longitude??'');const hasLat=latitudeText!==null&&latitudeText.trim()!=='';const hasLon=longitudeText!==null&&longitudeText.trim()!=='';if(hasLat!==hasLon){alert('Latitude and longitude must be supplied together.');return}const latitude=hasLat?Number(latitudeText):null,longitude=hasLon?Number(longitudeText):null;if((hasLat&&(!Number.isFinite(latitude)||latitude<-90||latitude>90))||(hasLon&&(!Number.isFinite(longitude)||longitude<-180||longitude>180))){alert('Coordinates are outside the valid latitude/longitude range.');return}const geocoding_source=hasLat?(prompt('Geocoding source (e.g. verified, imported, manual)',person.geocoding_source||'manual')||'manual'):null;const industry=prompt('Industry / sector (optional)',person.industry||'')||null;const r=await api(`/api/v1/admin/participants/${person.user_id}/segment`,{method:'PATCH',body:JSON.stringify({organization_size,category:nextCategory,organization_name,country,address_line1,city,region,postal_code,latitude,longitude,geocoding_source,industry})});if(r.ok)load();else alert('Could not update this participant.')}
 async function logout(){await api('/api/v1/auth/logout',{method:'POST'});location.href='/'}
 function download(path){window.location.assign(`${API}${path}`)}
 if(error)return <main className="gate"><Leaf/><h1>BloomAI Admin</h1><p>{error}</p><a href="/">Return to marketplace</a></main>;
 if(loading||!overview||!segments||!executive)return <main className="gate"><RefreshCw className="spin"/><p>Loading marketplace intelligence…</p></main>;
 const seg=segments[role]||{},k=executive.kpis||{};
 const growthData=Object.fromEntries((executive.category_growth||[]).slice(0,10).map(x=>[x.category,x.growth_percent]));
 return <div className="admin-shell"><aside><a href="/" className="brand"><Leaf/>BloomAI</a><nav><a className="active" href="#executive"><TrendingUp/>Executive</a><a href="#map"><Globe2/>World Map</a><a href="#segments"><BarChart3/>Segments</a><a href="#participants"><Users/>Participants</a><a href="#activity"><ShoppingCart/>Activity</a></nav><div className="admin-user"><ShieldCheck/><span><b>{me?.name}</b><small>Administrator</small></span></div></aside><main><header><div><span className="eyebrow">Executive marketplace intelligence</span><h1>Admin reporting & analytics</h1><p>Revenue, growth, retention, vendor performance and marketplace risk in one operating view.</p></div><div className="header-actions"><button onClick={load}><RefreshCw/>Refresh</button><button onClick={()=>download('/api/v1/admin/executive/export.csv')}><Download/>CSV</button><button onClick={()=>download('/api/v1/admin/executive/export.pdf')}><FileText/>PDF</button><button onClick={logout}><LogOut/>Logout</button></div></header>
 <section id="executive" className="stats executive-stats"><Stat icon={TrendingUp} label="Gross revenue" value={money(k.gross_revenue)} sub="Paid marketplace orders"/><Stat icon={ShoppingCart} label="Average order value" value={money(k.average_order_value)} sub={`${k.active_buyers} active buyers`}/><Stat icon={Activity} label="Checkout conversion" value={`${k.checkout_conversion_rate}%`} sub="Paid ÷ initiated orders"/><Stat icon={Users} label="Repeat purchase rate" value={`${k.repeat_purchase_rate}%`} sub={`${k.repeat_buyers} repeat buyers`}/><Stat icon={Globe2} label="Geocoding coverage" value={`${k.geocoding_coverage_rate||0}%`} sub={`${k.geocoded_participants||0} participants mapped`}/><Stat icon={Building2} label="Vendors" value={overview.users.vendors} sub={`${overview.users.customers} customers`}/></section>
 <div className="executive-controls"><label>Trend window<select value={months} onChange={e=>setMonths(Number(e.target.value))}><option value="6">6 months</option><option value="12">12 months</option><option value="24">24 months</option><option value="36">36 months</option></select></label><label>Inactive threshold<select value={inactiveDays} onChange={e=>setInactiveDays(Number(e.target.value))}><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option><option value="180">180 days</option><option value="365">365 days</option></select></label></div>
 <section className="charts executive-charts"><Trend title="Revenue trend" rows={executive.revenue_trends} labelKey="month" valueKey="revenue" format={money}/><Trend title="Customer acquisition" rows={executive.customer_acquisition} labelKey="month" valueKey="new_customers"/><Bars title="Category growth · last 30d vs prior 30d" data={growthData} valueSuffix="%"/></section>
 <section className="panel wide"><div className="panel-head"><div><h3>Vendor performance ranking</h3><p>Ranked by paid gross sales, then paid order volume.</p></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Vendor</th><th>Organization</th><th>Revenue</th><th>Paid orders</th><th>Unique customers</th><th>Products</th></tr></thead><tbody>{executive.vendor_ranking.map((v,i)=><tr key={v.vendor_id}><td>{i+1}</td><td><b>{v.vendor_name}</b></td><td>{v.organization_name||'—'}</td><td>{money(v.revenue)}</td><td>{v.paid_orders}</td><td>{v.unique_customers}</td><td>{v.products}</td></tr>)}</tbody></table></div></section>
 <section id="map" className="wide"><WorldMap points={executive.geographic_points||[]} geography={executive.geography||[]} coverage={executive.geographic_coverage||{}}/></section>
 <section className="charts"><section className="panel"><h3>Country-level fallback</h3><p className="muted">Participants without coordinates remain represented through their stored country so geographic reporting is never silently dropped.</p><div className="geo-grid">{executive.geography.slice(0,24).map(g=><div key={g.country} className="geo-cell"><b>{g.country}</b><strong>{money(g.revenue)}</strong><small>{g.customers} customers · {g.vendors} vendors</small></div>)}</div></section><section className="panel"><h3>Inactive-account detection</h3><p className="muted">Accounts with no recorded order, product or marketplace transaction activity within the selected threshold.</p><div className="inactive-list">{executive.inactive_accounts.slice(0,12).map(x=><div key={x.user_id}><span><b>{x.name}</b><small>{pretty(x.role)} · {x.country||'Unclassified'}</small></span><strong>{x.inactive_days}d</strong></div>)}{!executive.inactive_accounts.length&&<p className="muted">No inactive accounts at this threshold.</p>}</div></section></section>
 <section id="segments"><div className="toolbar"><div className="tabs"><button className={role==='vendor'?'active':''} onClick={()=>setRole('vendor')}>Vendors</button><button className={role==='customer'?'active':''} onClick={()=>setRole('customer')}>Customers</button></div><select value={size} onChange={e=>setSize(e.target.value)}><option value="">All sizes</option>{sizeOptions.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categoryOptions.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></div><section className="charts"><Bars title={`${pretty(role)} by organization size`} data={seg.by_size}/><Bars title={`${pretty(role)} by category`} data={seg.by_category}/></section></section>
 <section id="participants" className="panel wide"><div className="panel-head"><div><h3>{pretty(role)} directory</h3><p>Segment participants and add verified address/coordinate data for precise mapping.</p></div><label className="search"><Search/><input placeholder="Search name, email, organization or city" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Organization</th><th>Size</th><th>Category</th><th>Location</th><th>Map</th><th>Activity</th><th/></tr></thead><tbody>{shown.map(p=><tr key={p.user_id}><td><b>{p.name}</b><small>{p.email}</small></td><td>{p.organization_name||'—'}</td><td><span className="pill">{pretty(p.organization_size)}</span></td><td>{pretty(p.category)}</td><td>{[p.city,p.region,p.country].filter(Boolean).join(', ')||'—'}</td><td>{p.latitude!=null&&p.longitude!=null?<span className="mapped"><MapPin/>Mapped</span>:<span className="unmapped">Needs coordinates</span>}</td><td>{p.role==='customer'?`${p.activity.orders} orders · ${p.activity.paid_spend.toFixed(2)} spent`:`${p.activity.products} products · ${p.activity.orders_received} orders · ${p.activity.gross_sales.toFixed(2)} sales`}</td><td><button className="segment" onClick={()=>classify(p)}>Edit profile</button></td></tr>)}</tbody></table></div></section>
 <section id="activity" className="panel wide"><h3>Recent marketplace activity</h3><div className="activity">{activity.map((item,i)=><div key={`${item.type}-${i}`}><span className="dot"/><div><b>{item.summary}</b><small>{pretty(item.type)} · {new Date(item.occurred_at).toLocaleString()}</small></div>{item.amount!=null&&<strong>{item.currency} {item.amount.toFixed(2)}</strong>}</div>)}</div></section>
 </main></div>}

createRoot(document.getElementById('admin-root')).render(<AdminApp/>);
